const data = {
  defending: {
    bind: {
      a: [
        {
          id: 2,
          title: "A short (stair side) from truck",
          isActive: false,
          difficulty: "Easy",
          side: "Defending",
          essential: false,
          video: "429494645",
          bounces: 2,
          charges: 2,
          image1: "https://i.imgur.com/jqpILXo.jpg",
          image2: "https://i.imgur.com/IsmrdbC.png",
          map: "https://i.imgur.com/YLO6YtM.jpg",
          result: "https://i.imgur.com/0sZ7SgC.png",
          info:
            "Great dart for revealing A short while potentially revealing the staircase area. Align yourself so where the box is flush with the corner of the wall in the 1st image (same as market side dart). Then shoot right under the black metal box on the wall above it. It doesn't reveal the market side of A short, so be careful of that. It can scan the area, but they can easily lose line of sight. ",
        },
        {
          id: 3,
          title: "A short (market side) from truck",
          isActive: false,
          difficulty: "Easy",
          side: "Defending",
          essential: true,
          bounces: 2,
          charges: 1,
          video: "429494830",
          image1: "https://i.imgur.com/47Mbuhk.jpg",
          image2: "https://i.imgur.com/GWQUXgB.png",
          result: "https://i.imgur.com/N4RLnfi.png",
          map: "https://i.imgur.com/8tQpFui.jpg",
          info:
            "I think this is one of the best darts for defending A side. A lot of teams push up from market side of short, and not stair side, and this catches many teams off guard. Align yourself so where the box is flush with the corner of the wall in the 1st image (same as stair side dart). Then shoot right above the black spec on the wall on the 2nd picture. Very good dart that reveals the slow pushers. Mix this dart up with the stair side dart so it doesn't always get shot. You can aim higher on the wall, and the dart will end up on the doorway instead of the ground. There's a wire on the wall, make sure you don't hit the wire on the first bounce. ",
        },
        {
          id: 7,
          title: "A lobby from tower",
          isActive: false,
          difficulty: "Easy",
          side: "Defending",
          essential: true,
          bounces: 0,
          charges: 2,
          video: "429499774",
          image1: "https://i.imgur.com/95NQOUQ.png",
          image2: "",
          map: "https://i.imgur.com/cUNwwPG.jpg",
          result: "https://i.imgur.com/bRCE2NK.png",
          info:
            "This is for shower pushes and covers a deep area for you to get the orb if it doesn't scan anyone. Align the bottom left hand corner of your charge bar with the top left of the AC unit. It doesn't scan anyone in the red spot",
        },
      ],
      b: [
        {
          id: 4,
          title: "Fountain from B site",
          isActive: false,
          difficulty: "Easy",
          side: "Defending",
          essential: false,
          bounces: 0,
          charges: 2,
          video: "429499906",
          image1: "https://i.imgur.com/Sn1PK82.png",
          image2: "",
          map: "https://i.imgur.com/76eL2VY.jpg",
          result: "https://i.imgur.com/ReI4NvQ.png",
          info:
            "Landing anywhere near the fountain won't guarantee a full clearance of fountain side if someone decides to crouch near the fountain. This dart will land in the back, while giving you enough time to position yourself. It also forces people to to turn around and shoot it, giving you a chance to peek. Align the 4th brick so that it touches the right tip of the health bar lines. Make sure it's in the middle of the 4th bar as shown in yellow in the picture. If someone slow pushes, or holds the B long angle and stays back in the yellow spot, it scans the area, but they can easily loose line of sight behind the box. ",
        },
        {
          id: 5,
          title: "B short from hookah",
          isActive: false,
          difficulty: "Easy",
          side: "Defending",
          essential: true,
          bounces: 0,
          charges: 1,
          video: "429494715",
          image1: "https://i.imgur.com/1wMfkIE.png",
          image2: "",
          map: "https://i.imgur.com/yYNe7vy.jpg",
          result: "https://i.imgur.com/7qSAzmh.png",
          info:
            "This dart lands behind them on B short, forcing someone to turn around, or be scanned. It has a fast execution and enough travel time for you to peek out when it lands, even if you slow walk.  Aim where the red drapes meet the ceiling. Make sure you delay this shot, because most people chill in market for the first several seconds of a round. The only downside is that it doesn't reach into market. Thanks to redditor u/KhigenNA for finding this dart!",
        },
      ],
      mid: [],
    },
    split: { a: [], b: [], mid: [] },
    haven: {
      a: [
        {
          id: 9,
          title: "A lobby/garden from A tunnel/A site",
          isActive: false,
          difficulty: "Hard",
          side: "Defending",
          essential: false,
          video: "429845998",
          bounces: 0,
          charges: 2,
          image1: "https://i.imgur.com/r6UI8dl.png",
          image2: "",
          result: "https://i.imgur.com/fqYZ794.png",
          map: "https://i.imgur.com/f1yeA0D.jpg",
          info:
            "Great dart if you're holding sewers since it reveals A lobby, as well as some parts of garden. Align the tip of your shock dart icon on your HUD with the roof tile that protrudes out the most. Make sure the tip is exactly in the corner as shown in the image. As you can see in the map, it has a lot of blind spots, so be careful when using this dart not to bait your long player. Thanks to redditor u/KhigenNA for finding this dart!",
        },
        {
          id: 15,
          title: "A site from A link",
          isActive: false,
          difficulty: "Hard",
          side: "Defending",
          essential: true,
          video: "432707035",
          bounces: 0,
          charges: 0,
          image1: "https://i.imgur.com/yTzHDW6.jpg",
          result: "https://i.imgur.com/DKchKKq.png",
          map: "https://i.imgur.com/XJRxsC0.jpg",
          info:
            "Very great retake dart that covers 100% of hell, as well as other hiding spots. Align the corner of the box in the HUD with the corner of the window as shown in the picture below. Don't put it right next to it, make sure there's a very tiny gap. ",
        },
      ],
      b: [
        {
          id: 2,
          title: "Mid window from B site (A connector side)",
          isActive: false,
          difficulty: "Medium",
          side: "Defending",
          essential: false,
          video: "429846569",
          bounces: 1,
          charges: 2,
          image1: "https://i.imgur.com/sGRmHxN.png",
          image2: "",
          map: "https://i.imgur.com/4T6O1GL.jpg",
          result: "https://i.imgur.com/DElp82Z.png",
          info:
            "This dart lands on the window sill for mid window, which reveals a lot of mid/potentially grass, while also revealing window. Line up your crosshair with the bottom of the red text on the side of the metal container on B site. If you run, you should have enough time to peek with an awp. The great part about this dart is that if someone peeks up the courtyard, it will also spot them.",
        },
        {
          id: 3,
          title: "Mid window from B site (gong)",
          isActive: false,
          difficulty: "Easy",
          side: "Defending",
          essential: true,
          video: "429846506",
          bounces: 0,
          charges: 1,
          image1: "https://i.imgur.com/hcW2puP.png",
          image2: "",
          map: "https://i.imgur.com/4T6O1GL.jpg",
          result: "https://i.imgur.com/vPxGst0.png",
          info:
            "Very similar to the A connector side, this one will also land on the window sill at mid. This one you can use if you're coming into B from C side. Unlike the A connector side one, you're not exposed and safe from pushes. Just aim at the center of the wood that spans across the door. Unfortunately, this dart travels faster, and you won't have enough time to peek like the other dart. Use this dart if you're holding garage and your B guy needs help holding B site.",
        },
      ],
      c: [
        {
          id: 5,
          title: "C lobby from C site",
          isActive: false,
          difficulty: "Easy",
          side: "Defending",
          essential: true,
          video: "429846285",
          bounces: 0,
          charges: 1,
          image1: "https://i.imgur.com/u40JUZ2.png",
          image2: "",
          result: "https://i.imgur.com/zYEhMW7.png",
          map: "https://i.imgur.com/mAJRN79.jpg",
          info:
            "Great for teams with slow pushes into garage and C long, while being very quick to execute. Aim at the corner of roof in the picture.",
        },
        {
          id: 6,
          title: "C long/C Lobby from C site",
          isActive: false,
          difficulty: "Medium",
          side: "Defending",
          essential: false,
          video: "429846421",
          bounces: 2,
          charges: 3,
          image1: "https://i.imgur.com/3BHbkOj.png",
          image2: "",
          map: "https://i.imgur.com/SZ4B7UU.jpg",
          result: "https://i.imgur.com/ksTLOxc.png",
          info:
            "This dart reveals C long while also getting C lobby. In order for this dart to land, you need to aim as close as possible to the corner of the small section protruding from the wall, and aim right below the brown wood. It doesn't reveal all of C lobby, but it reveals enough from slow pushers. ",
        },
        {
          id: 10,
          title: "Grass from C link",
          isActive: false,
          difficulty: "Medium",
          side: "Defending",
          essential: true,
          video: "430529895",
          bounces: 1,
          charges: 2,
          image1: "https://i.imgur.com/KykLPwu.png",
          image2: "https://i.imgur.com/v8Xttiw.png",
          result: "https://i.imgur.com/p2efeaf.png",
          map: "https://i.imgur.com/OwavSsG.jpg",
          info:
            "Very useful dart for catching the garage pushers off guard, while also holding courtyard for your mid player. It reveals a lot of grass, while also potentially revealing into their spawn. Move along the back wall until you see a small opening where you see the wall at mid. Aim very slightly above the shadow. Careful for the tiny red on the map, but this arrow lands so fast, it should get a pulse off before they move. ",
        },
        {
          id: 11,
          title: "Attacker spawn from C site",
          isActive: false,
          difficulty: "Hard",
          side: "Defending",
          essential: true,
          video: "430529785",
          bounces: 0,
          charges: 2,
          image1: "https://i.imgur.com/RLn7eFk.png",
          image2: "https://i.imgur.com/VDB6Cg7.jpg",
          result: "https://i.imgur.com/TESgO2K.png",
          map: "https://i.imgur.com/wQbaVOx.jpg",
          info:
            "This dart reveals the entire back side of their spawn. You can reveal slow pushers from C, middle, garage, and A. It has a long travel time, but it comes down to fast, it's virtually undetected until it lands. Locate the small block in the 1st image, and align the tip of your shock bolt icon with the bottom right hand corner of that block. ",
        },
        {
          id: 14,
          title: "C site from C Link",
          isActive: false,
          difficulty: "Easy",
          side: "Defending",
          essential: true,
          video: "432704497",
          bounces: 1,
          charges: 2,
          image1: "https://i.imgur.com/jCjIlJh.png",
          result: "https://i.imgur.com/jwTVHtb.png",
          map: "https://i.imgur.com/Ih0Deha.jpg",
          info:
            "Easy retake arrow that lands in the back of C site when you're retaking. Aim along the wall about half way up from the shadow. ",
        },
      ],
      mid: [],
    },
    ascent: {
      a: [
        {
          id: 9,
          title: "A lobby/top mid from A site",
          isActive: false,
          difficulty: "Hard",
          side: "Defending",
          essential: false,
          video: "432604158",
          image1: "https://i.imgur.com/mdkYGf4.jpg",
          bounces: 0,
          charges: 1,
          map: "https://i.imgur.com/Oft1ut7.jpg",
          result: "https://i.imgur.com/OrQeo7G.png",
          info:
            "This lineup will reach back of mid, as well as A lobby. Line up the bottom of your hud so that it's touching the top left hand side of the stone above the entrance. ",
        },
        {
          id: 11,
          title: "Hell from heaven",
          isActive: false,
          difficulty: "Easy",
          side: "Defending",
          essential: false,
          video: "432604345",
          image1: "https://i.imgur.com/Bz0yqHR.png",
          image2: "https://i.imgur.com/OtRkGGn.png",
          bounces: 2,
          charges: 3,
          map: "https://i.imgur.com/rwvtuFa.jpg",
          result: "https://i.imgur.com/Mq4GLEz.png",
          info:
            "This is a retake dart for when you know someone's in hell. You can wallbang them once it scans. Aiming aimwhere on the green box should bounce it into hell, but make sure your position is align the the box. ",
        },
      ],
      b: [
        {
          id: 1,
          title: "B lobby/b main from B site",
          isActive: true,
          difficulty: "Easy",
          side: "Defending",
          essential: true,
          video: "431576728",
          image1: "https://i.imgur.com/E4NbMfQ.png",
          image2: "",
          bounces: 1,
          charges: 1,
          map: "https://i.imgur.com/L8bSkrL.jpg",
          result: "https://i.imgur.com/b7rNGTg.png",
          info:
            "Can cover mid/B lobby, as well as parts of B main, but doesn't fully cover either of them. Aim at top corner of the roof. ",
        },
      ],
      mid: [
        {
          id: 2,
          title: "Mid courtyard from mid cubby",
          isActive: false,
          difficulty: "Easy",
          side: "Defending",
          essential: false,
          bounces: 1,
          charges: 1,
          video: "431576892",
          image1: "https://i.imgur.com/fqeNnRT.png",
          image2: "",
          map: "https://i.imgur.com/gM8Rm7X.jpg",
          result: "https://i.imgur.com/7nou3yY.png",
          info:
            "This lineup will scan all of mid couryard from mid cubby, while staying hidden and out of sight. There are somy small blind spots, but for the most part, no one holds those positions if they are attacking. Aim where the 2 curves meet in the graffiti. ",
        },
        {
          id: 3,
          title: "Mid link from market",
          isActive: false,
          difficulty: "Easy",
          side: "Defending",
          essential: true,
          video: "431576817",
          bounces: 1,
          charges: 1,
          image1: "https://i.imgur.com/1MmBX0u.png",
          image2: "",
          map: "https://i.imgur.com/sranZUu.jpg",
          result: "https://i.imgur.com/2q1Ff50.png",
          info:
            "Lineup is for full scanning Mid link, but careful since it won't scan B lobby if you're against a team that slow pushes. Aim in the center right below the red cloth. ",
        },
        {
          id: 4,
          title: "Top mid from market",
          isActive: false,
          difficulty: "Easy",
          side: "Defending",
          essential: true,
          video: "431576644",
          image1: "https://i.imgur.com/oKUZGU7.png",
          image2: "",
          bounces: 1,
          charges: 3,
          map: "https://i.imgur.com/H8KL2X9.jpg",
          result: "https://i.imgur.com/9RrxFRD.png",
          info:
            "This should be your staple dart for top of mid, but should be mixed up with a mid link lineup to avoid prefire. If they fast peek you, you can perform this same dart from the back of mid. ",
        },
      ],
    },
  },

  attacking: {
    bind: {
      a: [
        {
          id: 6,
          title: "Lamps/U hall from A lobby",
          isActive: false,
          difficulty: "Hard",
          side: "Attacking",
          essential: true,
          bounces: 0,
          charges: 1,
          video: "429494765",
          image1: "https://i.imgur.com/HQ371jU.png",
          image2: "",
          map: "https://i.imgur.com/wlr4bi5.jpg",
          result: "https://i.imgur.com/64d0fHl.png",
          info:
            "One of the only darts that actually clears lamps. Has plenty of travel time for you to peek, and has a high tragetory to keep them occupied if they hear it. If it's shot, you know it has to be from lamps. Align your hud with the yellow spot on the bottom so that the tip touches the yellow paint on the metal box. There it a small, lighter spec of yellow on the tip of the yellow paint, make it so that the tip of your hud is fully covering the lighter spec of yellow. Careful for the red spot, if they hold a wide angle, it won't scan them. But if they hold a wide angle to expose themself from both sides, swing on them. Combine this dart with a phoenix or viper wall to easily get lamps control. ",
        },
        {
          id: 9,
          title: "Heaven from A lobby",
          isActive: false,
          difficulty: "Easy",
          side: "Attacking",
          essential: true,
          bounces: 0,
          charges: 1,
          video: "429499853",
          image1: "https://i.imgur.com/cXcmbh9.png",
          image2: "",
          map: "https://i.imgur.com/zgKQZfT.jpg",
          result: "https://i.imgur.com/HRubBJE.png",
          info:
            "Good dart for shower pushes when you know they have an awper since it fully exposes heaven. Has a quick execution. There isn't much to say about this dart other than point it at the left antenna. ",
        },
      ],
      b: [
        {
          id: 1,
          title: "Hookah from B short",
          isActive: true,
          difficulty: "Medium",
          side: "Attacking",
          essential: true,
          video: "433487668",
          bounces: 2,
          charges: 3,
          image1: "https://i.imgur.com/MLNZqD6.jpg",
          image2: "https://i.imgur.com/tS3QV6c.png",
          result: "https://i.imgur.com/WOLFL7M.png",
          map: "https://i.imgur.com/BtBpdy6.jpg",
          info:
            "There are plenty of hookah darts out there but this one fully clears Hookah 100% of the time. Line up against the wall so that the white space to the left of the brick disappears behind the wall. Then aim your crosshair on the left side of the crate about half way up. If they continue to hold hookah, you can slow push and be ready to wall bang the couch. It's relatively safe since you're darting from the left hand side of B short. Careful red spot, it's an off angle and that's the only spot that won't be scanned. I've yet to see someone hold from there, but be careful.",
        },
        {
          id: 8,
          title: "B site from B long",
          isActive: false,
          difficulty: "Easy",
          side: "Attacking",
          essential: true,
          bounces: 1,
          charges: 3,
          video: "429499814",
          image1: "https://i.imgur.com/fLKhhFY.png",
          image2: "",
          result: "https://i.imgur.com/WnRApI3.png",
          map: "https://i.imgur.com/JbKKLgQ.jpg",
          info:
            "Any dart that lands on B site to expose the most amount of spots should land here. It exposes cubby, under hookah, behind double box, as well as the entire back site. It can potentially scan someone inside the big box, but don't count on it because they can easily lose line of sight. Darts that land in the back, instead of the corner, function the same, but cannot potentially expose someone holding inside big box like this one can. Align your crosshair so that it's right above the tip of the sign. Anyone that holds back cubby will be exposed, but I wouldn't worry about it because back cubby is exposed by you sitting long. ",
        },
      ],
      mid: [],
    },
    split: { a: [], b: [], mid: [] },
    haven: {
      a: [
        {
          id: 1,
          title: "Garden from A site",
          isActive: true,
          difficulty: "Medium",
          side: "Attacking",
          essential: true,
          video: "430192154",
          bounces: 0,
          charges: 1,
          image1: "https://i.imgur.com/miCS1RO.png",
          image2: "https://i.imgur.com/vzPjMSe.png",
          map: "https://i.imgur.com/4jZEq6i.jpg",
          result: "https://i.imgur.com/cn7YdB3.png",
          info:
            "Pre round dart if you're holding sewers, it'll reach pretty deep back of spawn (I've scanned people holding C long angle), as well as covering garden pushes to A. Align yourself with again the big boxes in the first picture so that the edge of the box lines up with the edge corner of the intersecting wall. Then aim at the corner of the roof in the 2nd picture. Watch out of the red angles, especially the one next to the box since it won't scan those areas. It can scan window area, but don't count on it since losing line of sight is very easy. ",
        },
        {
          id: 4,
          title: "A site/heaven from A lobby",
          isActive: false,
          difficulty: "Hard",
          side: "Attacking",
          essential: false,
          video: "429846086",
          bounces: 0,
          charges: 2,
          image1: "https://i.imgur.com/gUdmiR6.png",
          image2: "",
          result: "https://i.imgur.com/7wGQni2.png",
          map: "https://i.imgur.com/0kTUm0J.jpg",
          info:
            "This dart is great since it clears site while also clearing heaven. First line up the bottom if your hud with the black line on the yellow wall. Also line up the 2 little tips so they are in the center of those 2 intentions along the roof. There are a lot of red spots on the map to watch out for, but luckily no one defends the site from those angles. Requires material quality to be on medium. ",
        },
        {
          id: 8,
          title: "B site from garden",
          isActive: false,
          difficulty: "Hard",
          side: "Attacking",
          essential: false,
          video: "429845924",
          bounces: 2,
          charges: 2,
          image1: "https://i.imgur.com/FSLaKE7.png",
          image2: "",
          map: "https://i.imgur.com/0BpWsWT.jpg",
          result: "https://i.imgur.com/9PdI7eS.png",
          info:
            "A very very difficult dart that I can't replicate 100% of the time, but I figure I add it because it's unique and very useful for someone who wants to master it. You can try to align yourself with the yellow spots on the image below, but it's still very difficul for me. It lands in the best spot on B, with almost not detection until it's too late. I won't even bother explaining how to do this one because I can't even consistently replicate it. But this dart with 2 brim smokes on either side of the metal container is a free entrance to B. Thanks to redditor u/KhigenNA for finding this dart!",
        },
        {
          id: 16,
          title: "A site/heaven from A long",
          isActive: false,
          difficulty: "Medium",
          side: "Attacking",
          essential: true,
          video: "432752209",
          bounces: 0,
          charges: 1,
          image1: "https://i.imgur.com/v9IwnSZ.jpg",
          result: "https://i.imgur.com/cCpln7i.png",
          map: "https://i.imgur.com/0kTUm0J.jpg",
          info:
            "Great dart for pushing into site, it clears heaven as well as a good portion of site. Make sure the top left corner of your charge bar lines up right in between the two rocks as shown in the image. Thanks to redditor u/jhn2 (discord JOHN#1154) for finding this dart!",
        },
      ],
      b: [],
      c: [
        {
          id: 12,
          title: "C site from C lobby (back C)",
          isActive: false,
          difficulty: "Medium",
          side: "Attacking",
          essential: true,
          video: "430912759",
          bounces: 1,
          charges: 2,
          image1: "https://i.imgur.com/bknngBE.jpg",
          image2: "https://i.imgur.com/qQoPd0q.jpg",
          result: "https://i.imgur.com/Ni44gGF.png",
          map: "https://i.imgur.com/KQvNrN8.jpg",
          info:
            "Really solid dart that should be mixed in with your garage push and C long push. It covers back of site, but most importantly, it covers the back left of the site where an awper can hold. Watch where I move to at the end of the video, make sure your darts clear that spot, very common awp spot. Align yourself so that the box is flush with the wall in the first image. Aim so that the left of the owl drone icon is flush with the small mountain in the background. ",
        },
        {
          id: 13,
          title: "C site from C lobby (platform)",
          isActive: false,
          difficulty: "Easy",
          side: "Attacking",
          essential: true,
          video: "430912690",
          bounces: 0,
          charges: 1,
          image1: "https://i.imgur.com/YltdB0I.png",
          result: "https://i.imgur.com/hPMoOBw.png",
          map: "https://i.imgur.com/mMXTgHg.jpg",
          info:
            "Similar to the last one, but a faster travel time. It lands on plat, so someone can be awping from the right of the back box, and it won't scan there. Aim right where the blue flag is hanging.",
        },
      ],
      mid: [],
      spawn: [
        {
          id: 7,
          title: "Garage from attacker spawn",
          isActive: false,
          difficulty: "Easy",
          side: "Attacking",
          essential: true,
          video: "432704455",
          bounces: 2,
          charges: 3,
          image1: "https://i.imgur.com/whFPDLL.png",
          result: "https://i.imgur.com/veMQLqe.png",
          map: "https://i.imgur.com/gy0eKkM.jpg",
          info:
            "This dart isn't meant to cover garage window, it's meant to cover the connector between the connector between garage and C site, while covering the rest of garage. Aim about half way up from the wall. Be careful for the red spot, since it won't scan that area, and it's a very common off angle hold spot. ",
        },
      ],
    },
    ascent: {
      a: [
        {
          id: 14,
          title: "A site from A main",
          isActive: false,
          difficulty: "Medium",
          side: "Attacking",
          essential: true,
          bounces: 0,
          charges: 1,
          video: "432604257",
          image1: "https://i.imgur.com/fIPZZSS.jpg",
          image2: "",
          map: "https://i.imgur.com/ebxttbg.jpg",
          result: "https://i.imgur.com/zXvYGnN.png",
          info:
            "Darts on A site should land here, it scans all the angles around the black box, as well as back of site. Align the bottom left of the charge meter with the stone as shown in the picture. ",
        },
        {
          id: 6,
          title: "A site from A lobby",
          isActive: false,
          difficulty: "Medium",
          side: "Attacking",
          essential: true,
          video: "432603212",
          bounces: 0,
          charges: 1,
          image1: "https://i.imgur.com/cxVPe6k.png",
          result: "https://i.imgur.com/XrDq3aU.png",
          map: "https://i.imgur.com/ebxttbg.jpg",
          info:
            "Scans back of site, all round the metal box, close left and close right, as well as behind the wooden box. The only spots it does not scan is hell and heaven. Aim right where the pointy white thing is as shown in the picture. ",
        },
        {
          id: 7,
          title: "A site from A main",
          isActive: false,
          difficulty: "Easy",
          side: "Attacking",
          essential: true,
          video: "432419840",
          image1: "https://i.imgur.com/uC5cJYL.png",
          bounces: 1,
          charges: 2,
          map: "https://i.imgur.com/NHJFiZU.png",
          result: "https://i.imgur.com/CgiNGYy.png",
          info:
            "Similar to the previous one, but it sacrifices the metal box for right side of heaven. Position yourself so that pipe on the wall is inbetween the door, then aim right at the bottom of the pipe. Careful since it leaves the left site unchecked. ",
        },
        {
          id: 8,
          title: "A heaven from A main",
          isActive: false,
          difficulty: "Easy",
          side: "Attacking",
          essential: false,
          video: "432419840",
          bounces: 1,
          charges: 2,
          image1: "https://i.imgur.com/a4kOvpo.png",
          map: "https://i.imgur.com/NHJFiZU.png",
          info:
            "This lineup will scan back of heaven, as well as close right on the site. Aiming anywhere on the upper half of the wall will scan it.",
        },
      ],
      b: [
        {
          id: 13,
          title: "Market from B main",
          isActive: false,
          difficulty: "Easy",
          side: "Attacking",
          essential: true,
          video: "432604384",
          image1: "https://i.imgur.com/qFKV4VZ.jpg",
          image2: "",
          bounces: 2,
          charges: 1,
          map: "https://i.imgur.com/oq080aB.jpg",
          result: "https://i.imgur.com/PjcVzaN.png",
          info:
            "This lineup will clear the awper that's rotating from mid, they won't expect it since it's coming from behind them. Aim right in between the 2 yellow lines at the top of the window. ",
        },
        {
          id: 12,
          title: "Shed from B main",
          isActive: false,
          difficulty: "Hard",
          side: "Attacking",
          essential: true,
          video: "432604471",
          image1: "https://i.imgur.com/BjuiCGx.jpg",
          image2: "",
          bounces: 1,
          charges: 3,
          map: "https://i.imgur.com/ZUG4kbD.jpg",
          result: "https://i.imgur.com/915GyJx.png",
          info:
            "This is one of the few hard, yet essential darts here. It's a very powerful dart that scans shed, the alley on close left, as well as right below market. Make sure you're crouching, and positioning the top left of your charge bar with the horizontal wood on the box, but make sure you're not flush next to it. put a tiny gap in between. ",
        },
      ],
      mid: [
        {
          id: 5,
          title: "Pizza/Mid bottom from mid top",
          isActive: false,
          difficulty: "Hard",
          side: "Attacking",
          essential: false,
          video: "432419685",
          bounces: 0,
          charges: 3,
          image1: "https://i.imgur.com/UssEkeE.jpg",
          map: "https://i.imgur.com/Ytvx1X7.jpg",
          result: "https://i.imgur.com/TE4eThr.png",
          info:
            "Scans both mid bottom and pizza area, but it's difficult to pull off. Please practice it before hand, so you can position yourself anywhere against the wall, as long as you aim above the corner where it's going to land. Imagine a horizontal line that's slightly below the roof, and a veritcal line that's always above the corner. I think this is a vital dart for mid, but there's another mid that covers nearly the same area that's a lot easier. ",
        },
        {
          id: 10,
          title: "Pizza/mid bottom from mid top",
          isActive: false,
          difficulty: "Medium",
          side: "Attacking",
          essential: false,
          video: "432603297",
          image1: "https://i.imgur.com/Bz0yqHR.png",
          image2: "https://i.imgur.com/OtRkGGn.png",
          bounces: 2,
          charges: 3,
          map: "https://i.imgur.com/Ytvx1X7.jpg",
          result: "https://i.imgur.com/aGEmbKy.png",
          info:
            "An easier version of the lineup mentioned earlier, but it's easier for it to be shot down by someone defending. Mix it up with the previous mid dart. Align yourself against the back wall so that a slanted black line is showing. Then aim at the bottom part of that slant. ",
        },
      ],
    },
  },
};

export default data;
